@failure_api_HostAddress = http://localhost:5082

### Register a new user
POST {{failure_api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "username": "bottas77",
  "password": "Bottas77!",
  "idGoogle": "google-id4"
}

### Login
POST {{failure_api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "testuser2",
  "password": "Password123!",
  "rememberMe": true
}

### Logout
POST {{failure_api_HostAddress}}/api/auth/logout