@failure_api_HostAddress = http://localhost:5082

### Register a new user
POST {{failure_api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "Password123!",
  "idGoogle": "google-id",
  "description": "This is a test user.",
  "link1": "http://example.com/link1",
  "link2": "http://example.com/link2",
  "link3": "http://example.com/link3"
}

### Login
POST {{failure_api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "Password123!",
  "rememberMe": true
}

### Get the token
{% 
  client.test("Token is received", function() {
    var response = JSON.parse(responseBody);
    client.global.set("jwt_token", response.token); // Ajuste conforme o formato da sua resposta
  });
%}

###