@failure_api_HostAddress = http://localhost:5082

### Register a new user
POST {{failure_api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "username": "testuser2",
  "password": "Password123!",
  "idGoogle": "google-id2",
  "link1": "http://example.com/link1",
  "link3": "http://example.com/link3"
}

### Login
POST {{failure_api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "testuser2",
  "password": "Password123!",
  "rememberMe": true
}

###