@failure_api_HostAddress = http://localhost:5082

### Follow a user
POST {{failure_api_HostAddress}}/api/follow/follow/bottas77

### Unfollow a user
PATCH {{failure_api_HostAddress}}/api/follow/unfollow/bottas77

### Allow a follow request
PATCH {{failure_api_HostAddress}}/api/follow/allow/bottas77

### Disallow a follow request
PATCH {{failure_api_HostAddress}}/api/follow/disallow/bottas77

### Deny a follow request
PATCH {{failure_api_HostAddress}}/api/follow/deny/bottas77

### Get followers
GET {{failure_api_HostAddress}}/api/follow/followers/testuser2

### Get following
GET {{failure_api_HostAddress}}/api/follow/following/bottas77

### Get follow requests
GET {{failure_api_HostAddress}}/api/follow/requests