@failure_api_HostAddress = http://localhost:5082

### Add or Update Reaction
POST {{failure_api_HostAddress}}/api/reaction/react
Content-Type: application/json

{
    "ReactionType": "Job",
    "JobApplicationId": 1,
    "ReactionName": "Like"
}

### Delete Reaction
PATCH {{failure_api_HostAddress}}/api/reaction/delete
Content-Type: application/json

{
    "ReactionType": "Job",
    "JobApplicationId": 1,
    "ReactionName": "Like"
}